python ./loadlocal.py -3 artillery_rain
python ./loadlocal.py 0 artillery_rain
python ./loadlocal.py 3 artillery_rain
python ./loadlocal.py 6 artillery_rain
python ./loadlocal.py 9 artillery_rain
python ./loadlocal.py 12 artillery_rain
python ./loadlocal.py -3 airstrikes
python ./loadlocal.py 0 airstrikes
python ./loadlocal.py 3 airstrikes
python ./loadlocal.py 6 airstrikes
python ./loadlocal.py 9 airstrikes
python ./loadlocal.py 12 airstrikes
python ./loadlocal.py -3 blitz
python ./loadlocal.py 0 blitz
python ./loadlocal.py 3 blitz
python ./loadlocal.py 6 blitz
python ./loadlocal.py 9 blitz
python ./loadlocal.py 12 blitz
python ./loadlocal.py -3 fighter_choppers
python ./loadlocal.py 0 fighter_choppers
python ./loadlocal.py 3 fighter_choppers
python ./loadlocal.py 6 fighter_choppers
python ./loadlocal.py 9 fighter_choppers
python ./loadlocal.py 12 fighter_choppers
python ./loadlocal.py -3 pistol
python ./loadlocal.py 0 pistol
python ./loadlocal.py 3 pistol
python ./loadlocal.py 6 pistol
python ./loadlocal.py 9 pistol
python ./loadlocal.py 12 pistol
python ./loadlocal.py -3 radio_comm
python ./loadlocal.py 0 radio_comm
python ./loadlocal.py 3 radio_comm
python ./loadlocal.py 6 radio_comm
python ./loadlocal.py 9 radio_comm
python ./loadlocal.py 12 radio_comm
python ./loadlocal.py -3 tank
python ./loadlocal.py 0 tank
python ./loadlocal.py 3 tank
python ./loadlocal.py 6 tank
python ./loadlocal.py 9 tank
python ./loadlocal.py 12 tank
python ./loadlocal.py -3 war
python ./loadlocal.py 0 war
python ./loadlocal.py 3 war
python ./loadlocal.py 6 war
python ./loadlocal.py 9 war
python ./loadlocal.py 12 war
python ./loadlocal.py -3 w_t
python ./loadlocal.py 0 w_t
python ./loadlocal.py 3 w_t
python ./loadlocal.py 6 w_t
python ./loadlocal.py 9 w_t
python ./loadlocal.py 12 w_t
python ./loadlocal.py -3 ww1
python ./loadlocal.py 0 ww1
python ./loadlocal.py 3 ww1
python ./loadlocal.py 6 ww1
python ./loadlocal.py 9 ww1
python ./loadlocal.py 12 ww1
python ./loadlocal.py -3 ww1_realistic
python ./loadlocal.py 0 ww1_realistic
python ./loadlocal.py 3 ww1_realistic
python ./loadlocal.py 6 ww1_realistic
python ./loadlocal.py 9 ww1_realistic
python ./loadlocal.py 12 ww1_realistic
